### ISSUE TITLE
Review the proposed new content category codes

### ISSUE THREAD

**Issue by sneft** [citizenlab/test-lists#27]
I have drafted a proposed set of revised content category codes which would replace the existing codes. The proposed set of codes are here:

https://github.com/citizenlab/test-lists/blob/master/lists/00-proposed-category_codes.csv

The aim here has been to streamline the categories, collapsing redundant categories and revising categories which were frequently confusing for list-creators. The goal was simplicity - fewer categories will be easier to use, prevent duplication and ideally limit miscategorization.

Alternative approaches considered were to adopt an existing category scheme wholesale (such as Netsweeper or Blue Coat). These generally have many more categories than the 30 proposed here, which can be a pro or a con depending on your needs.

Please feel free to offer feedback here. This list format is very much building on the prior ONI scheme, so I would love to hear comments based on alternative uses for the lists.

**Comment by hellais** [comment]
It was a pitty to not manage to meet up while in TO!

I noted some of the categories I found missing when importing the BOFH list here (I think this was before the new categories, hence I now realise a lot of them have a new valid category):
https://github.com/citizenlab/test-lists/blob/master/lib/lists/official/it/bofh.py#L46

I will comment in this ticket the ones that I think could still be integrated:

"Portale di link": "MISC"

Which would be something like "Directory", "Link index" (think dmoz, alexa, etc.)

"Phishing": "HACK",

This is a common occurrence in Italy for example where the postal police will block known fishing URLs by ISPs.

 "Riviste": "FEXP", 

This is "Magazines", this could fit within the news category, but it's description should be extended to include also non-news media. Perhaps NEWS could become MEDIA?

"Sito personale": "MISC", #XXX NEWCAT?

This would be "Personal website", like the personal work portfolio or a website meant to be accessed a reduced audience.

**Comment by sneft** [comment]
Yes, I wish we could have discussed this while you were here!

Here's my thoughts on the categories:

Directory, Link Index - I can imagine a category that includes these as well as 'web portals' could be useful. Such portals are particularly popular in Asia. Do you have a specific case in mind when you think of testing such link indexes?

Phishing - One of our general rules has been to avoid intentionally including sites which contain malicious content, so I don't think we'd want to include this.

Magazines - This is a good suggestion. I think we should include this as part of the NEWS category. (MEDIA was my initial choice for a code but I preferred to keep as many to four letters as possible, so it was strictly an aesthetic decision. I'm content either way.)

Personal website - I do see where this could fit in, but I'll explain our general thinking on this topic. We have usually preferred to be as specific and topical as possible in categorizing. So, as an example, if it was the personal website of a professor studying human rights, we could categorize as HUMR (human rights); if its the website of an LGBT activist we would categorize as 'LGBT', etc. I'm open to further thinking on this subject though.

Those are some of our general thoughts - please let me know what you think.

**Comment by hellais** [comment]
URLs of all of the above categories are present inside of the content loaded via the above linked code.

Regarding phishing websites in particular, in the case of Italy we really need this as it's a requirement for testing censorship here, since some of such websites are blocked on a national level.

On Personal websites, how would you categorise a personal website that of an artists (ex. a painter)?

**Comment by agrabeli** [comment]
Hi there. :)

As part of an initial review of the proposed new category codes, I think they look great overall. 

For starters, my suggestions include the following:

1.** Creation of a new category for "freedom of expression", which would be separate from "News Media".** 

A category code for "freedom of expression" could be "FEXP" (as included in the old category code). The main reason why I think it's important to separate "freedom of expression" from "news media" is because this would provide space to include websites which don't pertain to the reporting of news, but which fall under the broader category of free expression of views and ideas (personal blogs, which don't necessarily reflect political criticism, could be included here). 

2. **Creation of a new category for "intergovernmental organizations" (including, for example, the websites of the UN, OECD, WTO, etc.).** 

Such organizations publish material which certain governments might have an incentive to block locally...or not. Regardless, I think it could potentially be interesting to include such websites. A suggested category code for this could be "INTO". 

3. **Similarly to above: Creation of a new category for "non-governmental organizations" (including the websites of non-profit organizations, ranging from international ones like the Red Cross or Reporters Without Borders to those of smaller, local NGOs).**   

I realise that the type of content covered in the websites of NGOs often falls in other existing categories (such as "human rights", for example), and it makes sense to try to limit the categories to fewer ones (for practical reasons, as explained by @sneft ). I'm open to dropping this (proposed) category, though the reason why I am suggesting it is because it would provide space for adding NGO-specific websites and examining whether and to what extent their work is blocked in various countries around the world. A proposed category code for this could be "NGO". 

4. **Separation of "economic & financial topics" from "development & funding opportunities", by coding the first category as "ECON" and the second as "DEV".** (This is based on the old and new category codes of this sector.) 

I'm suggesting this separation of categories because, while they do in certain ways fall under the broader category of "economics", I think they describe very different situations and possibly very different limitations, if such websites were found to be blocked. For example, the blocking of websites pertaining to over-the-counter money exchanges can have very different limitations and interpretations to the blocking of websites which describe development agendas and funding opportunities (and I'm not sure if they should all be included under one broad category, as that could potentially limit the interpretation of results). 

In response to @hellais: Perhaps the personal website of an artist (for example) could fall under the new "Freedom of Expression" (FEXP) category (if created) or under the existing "Culture" (CULTR) category? 

In general, it seems to me that there is a sort of trade-off between limiting the categories (including more topics under broader categories, so as to enable contributors) and grouping websites under multiple categories. On the one hand, I agree with @sneft that there are benefits from grouping topics under broader categories (to potentially limit error, enable contributors, etc.), but on the other hand, I think that this can potentially lead to the misinterpretation of collected measurements when websites are broadly categorised. Thoughts?

Happy to discuss the above further. :)

**Comment by sneft** [comment]
Hi @agrabeli,

Thanks for contributing to the discussion. As you mention, in general our goal with this restructuring was to streamline our existing categories into more manageable and sensible ones, with an eye towards reducing the total number of categories we use. For that reason my default mindset is to limit the creation of new categories wherever possible.

Here's more specific responses:

**1 - Create Freedom of Expression category** 

As it stands now I would argue that our new NEWS category, combined with our broadened HUMR "Human Rights Issues" category (as well as Political Criticism POLR) will cover most of these use cases. Most often when I encounter a personal blog containing some sort of non-fiction commentary I do feel comfortable sorting into either HUMR or POLR. Are there any specific types of use cases you can imagine?


**2 - Create Intergovernmental Organizations category**

I think adding this category makes sense, and seems to be a useful pair with our new 'GOVT' Government category. 

**3 - Create NGO category**

I do appreciate the logic of this category, but again I'm concerned about duplication with the HUMR/ENV/POLR categories. For example, Greenpeace or Amnesty International are certainly NGOs but we'd prefer to be more specific and assign them to their more precise topic areas, such as ENV and HUMR. We have generally been working from the basis that, for simplicity, a URL should only be assigned to a single category where possible. This is not a hard and fast rule, but in my experience when we've opened the door to multiple categories we get situations where some people add upwards of four or five category codes to each URL, which I think is just adding noise.

**4 - Separate ECON/DEV categories**

Again I can see the logic here but I don't know how big a distinction needs to be made here. The example of over-the-counter money exchanges, if I'm interpreting it correctly, could be sorted as an E-Commerce (COMM) site. Are there any other examples?

As you mention, there is a trade-off between having more or less categories. While more may be useful for certain purposes, we find when they're too fine grained they can be interpreted and thus assigned differently by different people adding content to the lists, thus potentially negating the benefit. In other words, there's more detail possible but the variation in how they're used means the benefits of that detail are lost. 

Happy to discuss further!

Adam

**Comment by agrabeli** [comment]
Hi @sneft,

Thanks for your comprehensive response. :) 

In retrospect, I think you're right to say that most NGO websites probably do fall under existing categories, and that it's probably best to refrain from creating a new category for them. 

In regards to separating ECON/DEV categories, this was suggested because I think topics under ECON (such as e-commerce) are quite different to topics which fall under DEV (such as fund-raising, poverty, etc.) and that the separation of these two categories could potentially lead to the more accurate interpretation of results (especially if websites found to be blocked are in languages we don't understand). That said, I think it might make sense to leave this category as is for now, and re-evaluate whether a separation would be necessary at a later stage, based on the analysis of measurements. 

While I think you're right to say that websites which include "freedom of expression" could fall under NEWS, HUMR and POLR, I still think that the creation of a separate category for freedom of expression could be useful for including websites that aren't necessarily political per se, but which could still be interesting to test for censorship. @hellais' example of a painter's website could be included here. While I think that artistic websites, for example, which have a political nature are more likely to be blocked (and could be grouped under POLR), I think it would be good to still provide some space in the test lists for (personal) websites that aren't necessarily political and which don't necessarily address human rights issues. A space for such websites could be included in the suggested Freedom of Expression category. Do you perhaps have alternative suggestions for such websites? :)

**Comment by sneft** [comment]
**Re: ECON/DEV**

Perhaps we can clarify our terms somewhat. We have historically used DEV (to become ECON) to include material related to economic development and poverty alleviation, such as international aid organizations, the World Bank/IMF, etc. Such material may be seen as controversial by, for example, developing-world governments, who may see the material as critical of their rule, a foreign imposition on their nations, etc.

E-commerce, which would include online shopping sites such as Amazon and E-Bay, would normally be categorized as COMM.

Do you think these two categories allow for sufficient separation of the content?

**Re: Freedom of expression**

For something like the website of a controversial painter, we would normally use HAL (History, Arts and Literature), we we have proposed to rename to CULTR (Culture). I agree that content like this, as well as examples like personal blogs which aren't directly political, warrant a distinction from News media, but the hope is that the CULTR category can include personal writings, artistic expression, fiction, historical documents, etc. that aren't appropriately categorized as NEWS or POLR (Political Reform).

What do you think?

**Comment by agrabeli** [comment]
@sneft Thanks for the clarification. Yes, I think that ECON and COMM can allow for sufficient separation of the content. 

Re CULTR: Sure, I think what you're proposing could work. I think this can potentially be further evaluated when more URLs under this category are added across time.

**Comment by sneft** [comment]
Great, it sounds like we have somewhat of a consensus. I can add an Intergovernmental Organizations (IGO) category to our proposed list.

After this, any remaining issues to agree upon before converting?

**Comment by agrabeli** [comment]
Yes, please add the Intergovernmental Organizations (IGO) category to the proposed list. After this, I think we can convert the categories.

**Comment by sneft** [comment]
Great, I've pushed the update to add the IGO category.

**Comment by agrabeli** [comment]
Awesome, thanks :)

**Comment by agrabeli** [comment]
Hi @sneft, 

Hope you are well. :)

Some additional suggestions & questions in regards to the category codes include the following:

1. **Creation of a new category about technology:** Here we can include all blogs and websites which generally talk about technology, latest developments, etc. Currently, the existing categories (based on their descriptions) don't appear to accommodate such websites.

2. **Creation of a new category about education:** I think it would be interesting to include a category which hosts content related to education. Would you currently host content about education rights, for example, under HUMR?

3. **Re-naming the "Political criticism" category to "Political":** This would allow us to add websites which express political viewpoints, but which are not necessarily critical towards the status quo or governing party. 

4. Where do you suggest that websites about agriculture, farming and food security are added? It seems that the ENV category might be the one closest in terms of description? Should a new category be created?

5. Where should sites that talk about separatist movements go? Currently, the relevant category description only pertains to websites created by separatist movements, to my understanding. Could we change the category description of MILX to also include all other content that is about such movements?

6. Perhaps merge PORN with PROV so that they can include one category?

Thanks for your time! :)

**Comment by sneft** [comment]
Sorry for the delay responding!

I'll just address a few of your points for the moment:

3. Re-name 'Political criticism' - I think this is a fair point. We can rename this category and ensure that the description properly captures all of the content types we want included. 

4. Agriculture/food - My first instinct would be to put these types in the 'ECON' category, since this is the new category which is replacing 'DEV' and is meant to include development-related content. Of course, this is probably only one slice of what agriculture/farming/food type content would likely relate to, and as you say ENV for environmental issues would likely also apply in some cases. Are there others you can think of that don't fit into either of those?

5. Separatist movements - Agreed. We should adjust the category description to include both the websites of separatist movements and content talking about separatist movements. 

Adam

**Comment by sneft** [comment]
Thankfully we've finally completed the transition to the new category codes. I think it might make sense to rename the legends to reflect this. Perhaps:

00-LEGEND-category_codes.csv to 00-LEGEND-old_category_codes.csv
and
00-LEGEND-new_category_codes.csv to 00-LEGEND-category_codes.csv

This has the potential to break some things if people are automatically fetching based on these filenames, which we've been using for years. Any thoughts @hellais @rpanah?

**Comment by rpanah** [comment]
@sneft ICLab does not analyze the category codes, it just stores it when present in the test list. Therefore We don't use these files at the moment.

**Comment by hellais** [comment]
@sneft We do use the category codes files in a couple of places, though only in the backend so it should be fairly easy to implement a fix for that.

To minimise breakage though, I would suggest that in renaming `00-LEGEND-new_category_codes.csv` to `00-LEGEND-category_codes.csv`, the format for `00-LEGEND-new_category_codes.csv` is adjusted to look like the old format (i.e. `CategoryCode, CategoryName`), while `00-LEGEND-old_category_codes.csv` includes the mapping between old and new category codes.

When you do this change submit a PR with it so I can then also change the test-lists linter in travis to read the new category code from the correct file.

**Comment by hellais** [comment]
I am going to propose we close this ticket and discuss what might break or not in the eventual pull request with the name change.
