### ISSUE TITLE
Image Formats on Global List

### ISSUE THREAD

**Issue by RandomGuy48** [citizenlab/test-lists#894]
Kindly take a look on these image formats URLs first found at [global.csv](https://github.com/citizenlab/test-lists/blob/master/lists/global.csv)

Is there a good reason to keep all these image formats URLs in the Global test list? If so, is it better to categorize them as CTRL (Control Content)?

![image](https://user-images.githubusercontent.com/92066373/154186025-5fb1d9b3-822f-416c-892e-0cd0ba178765.png)

**Comment by xhdix** [comment]
Category is about the hostname itself, not the path or response data format.
I and Wikimedia chose the URL of the images because the root or `/robots.txt` of these hostnames will receive error (e.g., 404, 403, 503, etc).
You may see other extensions in these lists too. Like `ico`, `mp4` or even `zip`. Each of these usually has the same reasons or specific research reasons.

**Comment by RandomGuy48** [comment]
So they shouldn't be categorize as CTRL then, I'll close this issue
